apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: app-d-development

patches:
  - target:
      kind: CronJob
      name: app-d-batch
    patch: |
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - target:
      kind: ConfigMap
      name: app-d-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "development"
      - op: replace
        path: /data/BATCH_SIZE
        value: "10"
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"
