apiVersion: promoter.argoproj.io/v1alpha1
kind: TimedCommitStatus
metadata:
  name: soak-timer-app-a
  namespace: promoter-system
spec:
  promotionStrategyRef:
    name: app-a
  key: soak-timer
  duration: 2m
