apiVersion: promoter.argoproj.io/v1alpha1
kind: TimedCommitStatus
metadata:
  name: soak-timer-infra-e
  namespace: promoter-system
spec:
  promotionStrategyRef:
    name: infra-e
  key: soak-timer
  duration: 2m
