apiVersion: promoter.argoproj.io/v1alpha1
kind: TimedCommitStatus
metadata:
  name: soak-timer-app-c
  namespace: promoter-system
spec:
  promotionStrategyRef:
    name: app-c
  environments:
    - branch: environment/stage
      duration: 2m
