apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-b-prod-2

labels:
  - pairs:
      env: prod-2
    includeSelectors: true

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: app-b
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-b
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: app-b
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
