apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: gitops-promoter-example
  namespace: promoter-system
spec:
  github:
    owner: patjlm
    name: gitops-promoter-example
  scmProviderRef:
    name: github
