---
# Source: app-c/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-c-config
  labels:
    app: app-c
data:
  redis.conf: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    save 30 100
