apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-b
    env: prod-3
  name: app-b
  namespace: app-b-prod-3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-b
    env: prod-3
  type: ClusterIP
