apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-b-stage

labels:
  - pairs:
      env: stage
    includeSelectors: true

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: app-b
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-b
      spec:
        replicas: 2
