apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-2
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.github: ""
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    notifications.argoproj.io/subscribe.on-sync-failed.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/patjlm/gitops-promoter-example.git
    targetRevision: argocd-notifications-example
    path: app2
    helm:
      parameters:
        - name: revision
          value: $ARGOCD_APP_REVISION_SHORT
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Delete and recreate Jobs on every sync (forces new Job run)
