apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-change.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/patjlm/gitops-promoter-example.git
    targetRevision: argocd-notifications-example
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
