apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.github: ""
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    notifications.argoproj.io/subscribe.on-sync-failed.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/patjlm/gitops-promoter-example.git
    targetRevision: argocd-notifications-example
    path: app
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/revision: $ARGOCD_APP_REVISION_SHORT
      commonAnnotationsEnvsubst: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
