apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: app-c
  namespace: promoter-system
spec:
  gitRepositoryRef:
    name: gitops-promoter-example
  activePath: apps/app-c
  activeCommitStatuses:
    - key: ci-check
    - key: deploy
  environments:
    - branch: environment/development
    - branch: environment/integration
    - branch: environment/stage
      activeCommitStatuses:
        - key: timer
    - branch: environment/prod-1
      autoMerge: false
    - branch: environment/prod-2
      autoMerge: false
    - branch: environment/prod-3
      autoMerge: false
